version: 0.2

phases:
  install:
    commands:
      - echo Installing dependencies...

  build:
    commands:
      - echo "hello from service-a"
      - echo "hello from service-b"

artifacts:
  files:
    - '**/*'
